bleafcomix:
  config:
    compress_type:
      zip: ["zip", "cbz"]
      rar: ["rar", "cbr"]
    exclude_file1:
      - "."
      - ".."
      - "@eaDir"
      - "Thumbs.db"
      - ".DS_Store"
      - "@Recycle"
    exclude_file2:
      - "__MACOSX"
    include_file:
      - "jpg"
      - "gif"
      - "png"
      - "tif"
      - "bmp"
      - "jpeg"
      - "tiff"
      - "zip"
      - "cbz"
      - "rar"
      - "cbr"

server:
  port: 8888

---

spring:
  profiles: mac

bleafcomix:
  repository:
    default_root: "/User/bleaf/"

---

spring:
  profiles: win

bleafcomix:
  repository:
    default_root: "D:"
