bleafcomix:
  config:
    image_type:
      - "jpg"
      - "gif"
      - "png"
      - "tif"
      - "bmp"
      - "jpeg"
      - "tiff"
    compress_type:
      zip: ["zip", "cbz"]
      rar: ["rar", "cbr"]
    exclude_file1:
      - "."
      - ".."
      - "@eaDir"
      - "Thumbs.db"
      - ".DS_Store"
      - "@Recycle"
    exclude_file2:
      - "__MACOSX"


server:
  port: 8888

spring:
  profiles:
    active: win


---

spring:
  profiles: mac

bleafcomix:
  repository:
    default_root: "/User/bleaf/"

---

spring:
  profiles: win

bleafcomix:
  repository:
    default_root: "D:"
