comix:
  config:
    path:
      image_type:
        - "jpg"
        - "gif"
        - "png"
        - "tif"
        - "bmp"
        - "jpeg"
        - "tiff"
      zip_type: [zip, cbz]
      rar_type: [rar, cbr]
      exclude_file1:
        - "."
        - ".."
        - "@eaDir"
        - "Thumbs.db"
        - ".DS_Store"
        - "@Recycle"
      exclude_file2:
        - "__MACOSX"
    tools:
      encoding: utf-8
      decoding: euc-kr


server:
  port: 8888

spring:
  profiles:
    active: win

---

spring:
  profiles: service

comix:
  config:
    path:
      default_root: "/var/comix"

---

spring:
  profiles: mac

comix:
  config:
    path:
      default_root: "/User/bleaf/"

---

spring:
  profiles: win

comix:
  config:
    path:
      default_root: "D:"
